name: fellowworkerfront
description: Frontend application for fellow worker service.

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animate_gradient: ^0.0.2
  responsive_grid: ^2.1.0
  http: ^0.13.5
  flutter_web_auth: ^0.5.0
#  oauth2: ^2.0.1
#  url_launcher: ^6.1.7
#  uni_links: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/recruitment.png
     - assets/working.png
