name: fellowworkerfront
description: Frontend application for fellow worker service.

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animate_gradient: ^0.0.2
  responsive_grid: ^2.1.0
  http: ^0.13.5
  url_strategy: ^0.2.0
  flutter_web_auth: ^0.5.0
  flutter_secure_storage: ^7.0.1
  file_picker: ^5.2.5
  uuid: ^3.0.7
  intl: ^0.18.0
  json_annotation: ^4.8.0
  file_saver: ^0.1.1
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  source_gen: ^1.2.7

flutter:
  uses-material-design: true
  assets:
     - assets/recruitment.png
     - assets/working.png
