name: fellowworkerfront
description: Frontend application for fellow worker service.

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.32.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animate_gradient: ^0.0.3
  responsive_grid: ^2.4.4
  http: ^1.5.0
  url_strategy: ^0.2.0
  flutter_web_auth: ^0.6.0
  flutter_secure_storage: ^9.2.4
  file_picker: ^10.3.3
  uuid: ^4.5.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  file_saver: ^0.3.1
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  source_gen: ^4.0.1

flutter:
  uses-material-design: true
  assets:
     - assets/recruitment.png
     - assets/working.png
