version: "3"

services:
  # environment services
  postgres:
    container_name: postgresSQL
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: authorization
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  mongo:
    container_name: mongoDB
    image: mongo:6.0.3
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: fellow-worker
  rabbit:
    container_name: rabbitMQ
    image: rabbitmq:3.11-management
    ports:
      - "15672:15672"
      - "5672:5672"
