version: "2"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: authorization
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: fellow-worker
  rabbit:
    image: rabbitmq:3.11-management
    ports:
      - "15672:15672"
      - "5672:5672"
