package a.gleb.fellowworkerservice.configuration

import a.gleb.fellowworkerservice.configuration.properties.FellowWorkerConfigurationProperties
import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Configuration

@Configuration
@EnableConfigurationProperties(FellowWorkerConfigurationProperties::class)
class FellowWorkerConfiguration {
}