{
 "title": "fellow-worker-dashboards",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "cv-generator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total requests",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "http_server_requests_seconds_max{instance=\"cv-generator-service:7044\", uri=\"/api/v1/resume-download\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "System CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "system_cpu_usage{instance=\"cv-generator-service:7044\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "JVM total memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{instance=\"cv-generator-service:7044\"})/1000000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "JVM memory usage [nonheap]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"cv-generator-service:7044\", area=\"nonheap\"}/1000000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "JVM memory usage [heap]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"cv-generator-service:7044\", area=\"heap\"}/1000000",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "fellow-worker-service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total requests",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "http_server_requests_seconds_max{instance=\"fellow-worker-backend-service:4334\", uri=\"/**\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "System CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "system_cpu_usage{instance=\"fellow-worker-backend-service:4334\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "JVM total memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{instance=\"fellow-worker-backend-service:4334\"})/1000000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "JVM memory usage [nonheap]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"fellow-worker-backend-service:4334\", area=\"nonheap\"}/1000000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "JVM memory usage [heap]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"fellow-worker-backend-service:4334\", area=\"heap\"}/1000000",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "oauth2-server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Total requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{instance=\"oauth2-server-service:9001\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "system_cpu_usage{instance=\"oauth2-server-service:9001\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM total memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"oauth2-server-service:9001\"})/1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM memory usage [nonheap]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"oauth2-server-service:9001\", area=\"nonheap\"}/1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM memory usage [heap]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"oauth2-server-service:9001\", area=\"heap\"}/1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "client-manager-service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Total requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{instance=\"client-manager-service:8090\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "system_cpu_usage{instance=\"client-manager-service:8090\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM total memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"client-manager-service:8090\"})/1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM memory usage [nonheap]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"client-manager-service:8090\", area=\"nonheap\"}/1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM memory usage [heap]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"client-manager-service:8090\", area=\"heap\"}/1000000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}