global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "oauth2-app"
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["oauth2-server-service:9001"]
  - job_name: "client-manager-app"
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ "client-manager-service:8090" ]
  - job_name: "vacancy-resume-app"
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ "fellow-worker-backend-service:4334" ]
  - job_name: "document-generator-app"
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ "cv-generator-service:7044" ]
