server:
  port: 3000
  forward-headers-strategy: framework
  shutdown: graceful

spring:
  application:
    name: gateway-app
  lifecycle:
    timeout-per-shutdown-phase: 30s
  cloud:
    config:
      enabled: true
      fail-fast: true
      retry:
        initial-interval: 300
        max-attempts: 10
        max-interval: 3000

management:
  server:
    port: 2000
