server:
  port: 9091

spring:
  application:
    name: resume-app
  cloud:
    config:
      enabled: true
      fail-fast: true
      retry:
        initial-interval: 300
        max-attempts: 10
        max-interval: 3000

management:
  server:
    port: 8091
