server:
  port: 4334
  error:
    include-message: always
    include-binding-errors: always

springdoc:
  swagger-ui:
    oauth:
      client-id: message
      client-secret: c29tZXNlY3Rlcg==
      use-pkce-with-authorization-code-grant: true
  oAuthFlow:
    authorizationUrl: http://127.0.0.1:9001/oauth2/authorize
    tokenUrl: http://127.0.0.1:9001/oauth2/token

spring:
  application:
    name: fellow-worker
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://127.0.0.1:9001
  data:
    mongodb:
      authentication-database: admin
      database: fellow-worker
      port: 27017
      username: mongo
      password: mongo
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      default-binder: rabbit
      binders:
        rabbit:
          type: rabbit
      rabbit:
        bindings:
          fileSender-out-0:
            producer:
              binding-routing-key: generation
              routing-key-expression: '''generation'''
              transacted: true
          deleteSender-out-0:
            producer:
              binding-routing-key: remove
              routing-key-expression: '''remove'''
              transacted: true
      bindings:
        fileSender-out-0:
          destination: cv
        deleteSender-out-0:
          destination: cv

fellow-worker:
  unprotected-paths:
    - /api/v1/employee/get-all-resume
    - /api/v1/employee/get-resume-id
    - /api/v1/vacancy/vacancy-all
    - /api/v1/vacancy/id
    - /api/v1/vacancy/vacancies-by-skills
    - /api/v1/vacancy/vacancies-by-type
    - /api/v1/vacancy/vacancies-by-city
    - /api/v1/vacancy/vacancies-by-type-time
  security-constraints:
    - roles:
        - EMPLOYEE
      security-collections:
        - patterns:
            - /api/v1/employee/create-resume
            - /api/v1/employee/edit-resume
            - /api/v1/employee/delete-resume
            - /api/v1/employee/current-user-resume
    - roles:
        - COMPANY
      security-collections:
        - patterns:
            - /api/v1/vacancy/create
            - /api/v1/vacancy/edit
            - /api/v1/vacancy/delete-id

logging:
  level:
    web: INFO