server:
  port: 7001
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: user-service
  profiles:
    active: local
  config:
    import:
      - configserver:http://localhost:7004
      - vault://
  cloud:
    vault:
      authentication: token
      kv:
        backend: secrets/fellow-worker
        application-name: ${spring.application.name}
        enabled: true
        profiles:
          - local
      enabled: true
      uri: http://localhost:8200
      token: ${VAULT_TOKEN}
    config:
      enabled: true
      uri: http://localhost:9099
      fail-fast: true
      retry:
        initialInterval: 300
        maxAttempts: 10
        max-interval: 3000
  jpa:
    show-sql: true

management:
  server:
    port: 7002
  endpoints:
    web:
      discovery:
        enabled: false
      exposure:
        include: health, prometheus
    access:
      default: read_only
  endpoint:
    health:
      probes:
        enabled: true
      access: read_only
    metrics:
      access: read_only
    prometheus:
      access: read_only
  defaults:
    metrics:
      export:
        enabled: false
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    root: info