server:
  port: 8090
  error:
    include-message: always
    include-binding-errors: always

springdoc:
  swagger-ui:
    oauth:
      client-id: message
      client-secret: c29tZXNlY3Rlcg==
      use-pkce-with-authorization-code-grant: true
  oAuthFlow:
    authorizationUrl: http://127.0.0.1:9001/oauth2/authorize
    tokenUrl: http://127.0.0.1:9001/oauth2/token

spring:
  application:
    name: client-manager
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://${OAUTH2_SERVER_URL}:9001
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://${DATASOURCE_URL}:5432/authorization

client-manager:
  cors:
    enabled: true
    allowed-origins:
      - "*"
    allowed-origins-all: true
    allowed-methods:
      - "*"
    allowed-headers:
      - "*"
  security-constraints:
    - roles:
        - COMPANY
        - EMPLOYEE
        - ADMIN
      security-collections:
        - patterns:
            - /api/v1/account/edit
            - /api/v1/account/delete
            - /api/v1/account/change-password
            - /api/v1/account/current
    - roles:
        - ADMIN
      security-collections:
        - patterns:
            - /api/v1/support/disable-account
            - /api/v1/support/accounts
            - /api/v1/support/account-by-username
  unprotected-patterns:
    - /api/v1/account/create
    - /api/v1/account/data

logging:
  level:
    web: INFO
