server:
  port: 9001
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: oauth2-server
  profiles:
    active: local
  config:
    import: configserver:http://localhost:9099
  cloud:
    config:
      enabled: true
      uri: http://localhost:9099
      fail-fast: true
      retry:
        initialInterval: 300
        maxAttempts: 10
        max-interval: 3000
  jpa:
    show-sql: true
  datasource:
    username: postgres # TODO: move to Vault.
    password: postgres # TODO: move to Vault.

fellow-worker-oauth2-server:
  encoder-strength: 13 # TODO: move to Vault.

management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: info