spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authorization
    driver-class-name: org.postgresql.Driver
  threads:
    virtual:
      enabled: true
  cloud:
    stream:
      default-binder: rabbit
      binders:
        rabbit:
          type: rabbit
      rabbit:
        bindings:
          remove-user-out-0:
            producer:
              use-confirm-header: true
              routing-key-expression: '''remove-user-event'''
              exchange-type: direct
      bindings:
        remove-user-out-0:
          destination: fellow-worker
  rabbitmq:
    publisher-returns: true
    publisher-confirm-type: correlated

fellow-worker-oauth2-server:
  unprotected-patterns:
    - "/assets/**"
    - "/login"
    - "/actuator/**"
    - "/error"
    - "/v3/api-docs/**"
    - "/api/v1/account/create" # create new account.
  defaultClients:
    - default-client-id: message
      default-client-secret: c29tZXNlY3Rlcg==
      default-access-token-time-to-live: 30 # minutes
      default-refreshToken-time-to-live: 3 # days
      client-secret-days-ttl: 90
      default-redirect-uris:
        - "https://oauth.pstmn.io/v1/browser-callback"
  rmq:
    await-timeout: 40000
  default-roles:
    - role-name: SYSTEM
      display-name: System
      is-map-on-default-client: true
    - role-name: ADMIN
      display-name: Administrator
      is-map-on-default-client: false
  issuer-url: http://127.0.0.1:9001
  send-out-box-message:
    cron: 0 0 * * * *
  remove-expired-session-task:
    cron: 0 0 0 * * *
    day-offset: 90
  token-url: http://127.0.0.1:9001/oauth2/token
  authorization-url: http://127.0.0.1:9001/oauth2/authorize
  cors:
    allowed-origins: "*"
    allowed-methods:
      - "*"
    allowed-headers:
      - "*"
    allowed-origin-patterns:
      - "*"